name: Check PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  HUSKY: 0
  CI: true

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Perform checks
        run: |
          yarn install --frozen-lockfile
          yarn tsc
          yarn lint
          yarn prettier
